### ISSUE TITLE
Live Reload Chrome Extension Doesn't Automatically Activate

### ISSUE THREAD

**Issue by nahtnam** [napcs/node-livereload#106]
## What version are you using? (Don't say latest. Be specific.)
v0.6.2

## Expected result
When I load my page, I would assume that the chrome extension would automatically enable so that live reloads would happen.

## Actual result
The page loads, however the chrome extension doesnt automatically enable. Only after a few changes when I realize that the page isnt being reloaded will I click the chrome extension button where it will enable.

## Steps to reproduce issue
(Not trying to advertise my project, but it is reproducible through it)
1. Install chrome extension
2. Create a new project
```
npm install -g konstructor-cli
konstructor-cli new test
cd test
npm install
npm run dev
```
3. Load [http://localhost:3000](http://localhost:3000)
4. Change `/app/hello/index/index.marko`
5. Go back to the web page and notice how nothing has changed.
6. Click the chrome extension icon in the top right to enable it
7. Make one more change to the file
8. Go back to the web page and you'll see it instantly update

Source code related to the livereloading: https://github.com/konstructorjs/konstructor/blob/master/src/app/index.js#L22-L33

## Why is this important?
Its a lot more user friendly if the chrome extension automatically enables. If you run an `ember-cli` application, it will automatically enable live-reloading which is why I think this has to do with this package rather than the chrome extension.

**Comment by napcs** [comment]
Are you sure emberCLI isn't just injecting the JS onto the page and bypassing the extension? There's no way for the NodeJS app to talk to the extension directly without *something* being on the page for the browser to recognize.

**Comment by nahtnam** [comment]
Looking at this: https://github.com/ember-cli/ember-cli-inject-live-reload, it looks like ember-cli does inject the script. I thought there was some sort of api that ember-cli was interacting with, but I was wrong.

My mistake, thanks.
