### ISSUE TITLE
Reloads page with dead web server

### ISSUE THREAD

**Issue by doublejosh** [napcs/node-livereload#107]
## Version
0.6.2

## Expected result
Changing file reloads the page with the server still running.

## Actual result
The page is reloaded with the web server dead.  I must visit the localhost root, which restarts the server (`http://127.0.0.1:8080`) then visit the specific page: `http://127.0.0.1:8080/mypage.html`.  The same behavior happens when I edit the root index file... dead server.

## Steps to reproduce issue
Change a file that is not the root `index.html` file.  This is a static site.

## Why is this important?
Basic functionality.

**Comment by doublejosh** [comment]
Was able to get it working fine by first starting my `http-server` in one terminal tab, and using a second to run `livereload`.  Not ideal, but works.

**Comment by napcs** [comment]
I'm sorry, can you explain exactly what you're doing? I need steps to reproduce this on my end.

Editing an HTML page that LiveReload is watching will trigger the browser to reload that page. Since it doesn't serve pages, I am confused by what you mean by "web sever dead."

**Comment by doublejosh** [comment]
I think you can ignore this. I was testing several implementations and thought this library was functioning as both serving the files and live-reload (others do).  Thanks.
