### ISSUE TITLE
Feature request: Would be nice if -w timer reset when new changes detected

### ISSUE THREAD

**Issue by SystemDisc** [napcs/node-livereload#108]
If I do:
`livereload 'dist/server/main.js, dist/client/main.js' -w 1000`
and `dist/server/main.js` or `dist/client/main.js` change, the 1000ms timer starts and when the timer reaches zero livereload tells the browser to refresh.

Howevever, if `dist/server/main.js` or `dist/client/main.js` change, and during the 1000ms delay/timer `dist/server/main.js` or `dist/client/main.js` change again, the timer does not reset. In my setup, that could result in the browser refreshing when the files are not ready.

Ideally, in my setup, I'd like the timer to start when a change is detected, and the timer to be reset if a change is detected during that countdown. This would mean that livereload would only tell the browser to refresh if a change was detected and it's been at least X milliseconds (where X is the value after -w) since the last detected change.

It would be fine with me if instead of changing how -w worked, a new parameter was added. However, I think adding this would be an improvement on how -w works.

**Comment by napcs** [comment]
I get what you're asking - but can you clarify why you're using the -w flag in the first place? You almost never need it unless your OS is being incredibly silly. The file watcher under the hood should just work as you describe.

**Comment by SystemDisc** [comment]
I use `-w` because I'm using Angular 4 with AoT, webpack, ExpressJS with server-side rendering, and nodemon. There's some time between the files being built/updated and them being available to the browser (i.e. node has to restart, start listening, and be ready to serve information). Also, my request for it to wait until things settle down is because webpack might start rebuilding things, and I might save a second file during that process, which will cause webpack to rebuild again after it's finished.

**Comment by SystemDisc** [comment]
https://github.com/SystemDisc/ng-universal-starter

**Comment by SystemDisc** [comment]
If I remove `-w` in that project, the browser reloads before node is ready and I get a connection error in Chrome.

**Comment by napcs** [comment]
Ah. Ok. With that setup, you shouldn't really be using livereload. You probably should look at webpack-dev-server or one of the other plugins for webpack and reloading.

**Comment by SystemDisc** [comment]
I'm sorry. That's not an option. Express needs to be the server for Angular 4 server-side-rendering to work.

I think for development, `livereload` works fine. It could work better, and I think a possible solution would be to manually set up `livereload` in `srv/server/main.ts` instead of using `livereload CLI` with `connect-livereload`. However, I still think what I described in the first post would be a beneficial feature to have.

**Comment by SystemDisc** [comment]
On second thought, I don't think I can set up `livereload` in `srv/server/main.ts` since the websocket will close when the server is restarted via nodemon.

**Comment by napcs** [comment]
The way the timeout is implemented isn't currently something I can just reset. I'm happy to review a pull request, but it's really not what the timeout is intended for.

Would something like this work? Start livereload with your nodemon script:

```
// livereload setup

const liveReload = require('../lib/livereload');
const liveReloadServer = liveReload.createServer({
  port: 35729,
  debug: true,
});

liveReloadServer.watch(__dirname);

// some other setup

nodemon.on('restart', function() {
    setTimeout(function() {
      liveReloadServer.refresh('');
    }, 3000);
});
```

I know this worked for someone else who needed livereload to trigger reloads when their server restarted.

**Comment by SystemDisc** [comment]
This looks promising. I'll get back to you on this.

**Comment by SystemDisc** [comment]
Thank you.

**Comment by SystemDisc** [comment]
Can I use the livereload CLI, have it not watch a directory/file, and tell it to refresh from my code? What you've suggested will not work for me.

**Comment by napcs** [comment]
No. But you could leave this out of the above code:

```
liveReloadServer.watch(__dirname);
```

Then livereload won't watch. But calling 

```
      liveReloadServer.refresh('');
```

will still send the ping.


Working up a fix to #110 to support this more gracefully - it fails to shutdown correctly in the current release.

**Comment by napcs** [comment]
Just an update - 0.6.3 is out and it fixes #110

**Comment by SystemDisc** [comment]
For future reference, this is what I ended up putting in my `webpack.config.js`

```javascript
if (process.env.NODE_ENV === 'development') {
	const { spawn } = require('child_process');
	let server;
	let startServer = () => {
		console.log('starting server');
		server = spawn('npm', ['run', 'server:dev']);
		server.on('exit', () => {
			startServer();
		});
		server.stdout.pipe(process.stdout);
		server.stderr.pipe(process.stderr);
		console.log('sending livereload signal');
		lrServer.refresh('');
	};
	let livereload = require('livereload');
	let lrServer = livereload.createServer();
	serverConfig.plugins.push(function() {
		this.plugin('done', (stats) => {
			console.log('build done');
			if (server) {
				console.log('stopping server');
				server.kill();
			}
			else {
				startServer();
			}
		});
	});
}
```

**Comment by SystemDisc** [comment]
Also, in the case where it takes a bit for your server to start up and the server outputs something like log "`listening on http://localhost:3000/`" when it's ready, you can do the following:

```javascript
server.stdout.on('data', (data) => {
	if (/^listening/.test(data)) {
		console.log('sending livereload signal');
		lrServer.refresh('');
	}
});
```

This would make sure livereload only causes the page to refresh when the server is ready.
