### ISSUE TITLE
watcher is undefined in close()

### ISSUE THREAD

**Issue by donaldpipowitch** [napcs/node-livereload#110]
## What version are you using? (Don't say latest. Be specific.)

Latests 😄 0.6.2.

## Expected result

Call `close()` before `watch()` without an error.

## Actual result

```
TypeError: Cannot read property 'close' of undefined
```

## Steps to reproduce issue

It looks like `watcher` is set when `watch()` is called. But I call `refresh()` manually and don't use `watch()`. However I'd like to close the server with `close()`. Currently this throws, because it expects `watcher` to be set.

## Why is this important?

I use `refresh()` manually and inside a webpack build and don't use `watch()`.

**Comment by napcs** [comment]
@donaldpipowitch thanks for reporting this. 0.6.3 was released to npm.

**Comment by donaldpipowitch** [comment]
Thank you for the fix! ♥️
