### ISSUE TITLE
Manually refreshing browser

### ISSUE THREAD

**Issue by GCorbel** [napcs/node-livereload#114]
## What version are you using? (Don't say latest. Be specific.)

0.6.3

## Expected result

Allow to refresh the browser when we do a command line.

## Actual result

We can only refresh when a file is changed.

## Why is this important?

I want to reload browser with a shortcut in Vim. I don't want to reload always because it's not always useful and I prefer to keep the control. Furthermore, I don't want to run livereload everytime. I tried solutions with x-dotool but this is a bit unreliable and livereload seems to be more stable because of the direct connection with the browser.

At the moment, I can do something like `livereload /tmp/file.js` and `touch /tmp/file.js` when I want to reload but it looks like a hack and it's not very clean. I can do this command line : `kill $(ps a | grep livereload | grep -v grep | awk '{print $1}') && livereload /tmp/test.js & sh -c "sleep 2 && touch /tmp/test.js"` to run the server, reload and exit.

I think there is some solutions : 

- Run the websocket server and do a command to connect to the websocket server and say to reload all browsers;
- Run the websocket server and do an HTTP request to the websocket server;
- Do the equivalent of my super awesome command line;
- Do an HTTP request directly to the browser extension;

I suppose the last one is not possible because we must have a server that run somewhere.

What you think? Is it something useful?

**Comment by GCorbel** [comment]
Finally, I created a service like this : 

```
[Unit]
Description=Livereload server
After=network.target

[Service]
Type=simple

ExecStart=/home/dougui/.npm-global/bin/livereload /tmp/touch.js

Restart=on-failure

# Configures the time to wait before service is stopped forcefully.
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target
```

And created this shortcut in vim `map <leader>n :w<cr>:!touch /tmp/touch.js<cr><cr>`.

Still a hack but it works.

**Comment by napcs** [comment]
Livereload is designed to reload the HTML page when it changes. If you want manual reloading, xdotool is what you want. This script from the entrproject works well for me. http://entrproject.org/scripts/reload-browser
