### ISSUE TITLE
Update ext/livereload.js to version 2.2.3 (or 2.3.0)

### ISSUE THREAD

**Issue by smhg** [napcs/node-livereload#117]
## What version are you using? (Don't say latest. Be specific.)
0.6.3

## Expected result
ext/livereload.js to be either 2.2.3 or (today to be released) 2.3.0

## Actual result
ext/livereload.js is currently version 2.2.2

## Why is this important?
The 2.2.3 version (also on NPM) fixes the long overdue `ProtocolError is not defined` error.
This means an update can replace #116 so I'll close that.

**Comment by napcs** [comment]
@smhg This is awesome. Thank you. Somehow I've not been seeing notifications on these issues and I'm not sure why. I'll make sure this is in the next release which I'm trying to prep. Could you possibly help me out by just making a PR that includes the new version of the external file?

**Comment by smhg** [comment]
PR #118 should be it. Let me know if anything is unclear.

**Comment by napcs** [comment]
Awesome!

**Comment by smhg** [comment]
@napcs it would be awesome if you could release a new version with the updated client.

**Comment by napcs** [comment]
@smhg see other message - 0.7.0 is released to npm.

**Comment by smhg** [comment]
Thx a lot! I forgot I already pinged you in another issue. My appologies.
