### ISSUE TITLE
browser connection problems with docker.

### ISSUE THREAD

**Issue by laurencefass** [napcs/node-livereload#120]
## summary

I am running a node js application in a docker container in a virtualbox VM running on a windows 10 host where i am also running the browser to load the page from the server. this bit works fine but the client is having problems connecting to livereload.  i am using the following command to start livereload

> livereload . -u true -w 1000 -d

## What version are you using? (Don't say latest. Be specific.)
"livereload": "^0.7.0",

## Expected result
browser reload when i change source file.

## Actual result
when i load/reload the page i get the following output from livereload this goes round in repeat.

```
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.3.0","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client closed connection...

```
when i save a source file i see...

```
Reloading: /usr/src/app/index.html

Client closed connection

Browser connected.

```

this output repeats each time i save changes to source files.

## Steps to reproduce issue
normal procedure start livereload and edit a source file....

## Why is this important?
not working through network.

**Comment by napcs** [comment]
Hmmm. The troubling bit is:

```
Client closed connection...
```

after the handshake.   I'm betting the client-side script can't talk to LiveReload. Are you using a browser plugin or are you dropping JavaScript on your pages to get the reloading to work?

**Comment by laurencefass** [comment]
I'm including the javascript in the web pages.... Livereload works fine when editing files from within the container and this looks like a problem with livereload editing files in a (mounted?) volume with a host editor (actually a virtualmin host of a boot2docker virtual machine). It would be great to edit files from (either) host. Looks like events not getting fired on save (due to save happening on windows machine).

**Comment by napcs** [comment]
@laurencefass is there any way you can provide me a simplified version of what you're doing so I can try to reproduce it?

**Comment by laurencefass** [comment]
OK so I have windows 10 host (aka virtualbox host)->virtualbox guest (aka docker host)->docker container. Both my browser (firefox) and code editor (vscode) are running on the windows 10 host. the virtualbox host and guest have a shared folder setup which is how i can see the files in the VM guest on the windows host.

Livereload doesn't respond when i update files pushed to the container from a mounted folder (aka a "mounted volume") docker host when I modify the files from the VM host. If I save an affected file from the docker host (the VM guest) OR from inside the container Livereload picks up on the save and reloads the browser.

**Comment by laurencefass** [comment]
sure thanks for your time and attention on this.

- install docker toolbox.
- open windows 10 visual studio code.
- open windows 10 browser
- docker-machine start default (to run with vm)
- run a container with a node.js server app running with Livereload.
- edit the code and save from within the container. result: LiveReload works, browser reloads
- edit the code and save from within visual studio code. result: LiveReload fails to detect change, browser doesnt reload.

if this is insufficient detail let me know and i'll re-run from the start and see what i might have missed.

**Comment by napcs** [comment]
@laurencefass What if you increase the wait time to 5000?

**Comment by laurencefass** [comment]
thanks. there are a lot of elements working together here. wait time of what?

**Comment by laurencefass** [comment]
so something like:
$ livereload . -w 5000 -d
i will give it a try...

**Comment by napcs** [comment]
@laurencefass probably

livereload . -u true -w 5000 -d

You still want to tell it to use polling.
