### ISSUE TITLE
Vulnerability for Prototype pollution attack found

### ISSUE THREAD

**Issue by maevadevs** [napcs/node-livereload#121]
## What version are you using? (Don't say latest. Be specific.)
livereload@0.7.0 
## Expected result
(+) No known vulnerabilities found
## Actual result
(+) 1 vulnerability found

![screenshot](https://user-images.githubusercontent.com/6579094/38452207-20c17cfa-3a05-11e8-8b19-f6d688e12b3e.png)

**Prototype pollution attack** 
More Info  │ https://nodesecurity.io/advisories/566 
## Steps to reproduce issue
1. Install Global `nsp`: `npm i -g nsp`
2. `cd` into `livereload` folder: `cd [...]/.nvm/versions/node/v8.11.1/lib/node_modules/livereload`
3. Run `nsp check`
## Why is this important?
This vulnerability has the potential to allow attack that can be used to overwrite existing properties, causing a potential denial of service.

**Comment by napcs** [comment]
Attempting to bump versions of things to fix this has broken LiveReload so I'm a bit stalled. Working on it.

**Comment by napcs** [comment]
Fixed by #127
