### ISSUE TITLE
refused to execute script from because its mime type

### ISSUE THREAD

**Issue by eniniz** [napcs/node-livereload#123]
Hi, I'm trying to use node-livereload to benefit from live reload, but it doesn't work, previously I was using apache http server and it works fine , but now when I use the live reload server I get : 
`Refused to execute script from '' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
foreach js, css file in my project.

**Comment by napcs** [comment]
@eniniz Please resubmit this and provide the information requested in the issue template. I don't know enough about your environment to attempt to debug this.
