### ISSUE TITLE
Update livereload-js to 3.0.0

### ISSUE THREAD

**Issue by smhg** [napcs/node-livereload#126]
Would it be possible to update the livereload client script with the latest version?
You can use the raw file(s) from this tag:
https://github.com/livereload/livereload-js/tree/v3.0.0/dist

The major change is the source is now modern JS instead of coffeescript. This shouldn't break anything and it would be great to have more real-world exposure.

## What version of Livereload are you using?

0.7.0

## What OS are you using?

Ubuntu 18.04

## What web browser are you using? (Browser name and specific version please)

Chrome 73.0.3683.86 

## Expected result

Use latest livereload client script version.

## Actual result

The previous livereload client script version.

**Comment by napcs** [comment]
@smhg Absolutely will evaluate this and make sure it works. Really happy if someone else wants to do the work and test it for me tho. :)

**Comment by napcs** [comment]
@smhg This is done in https://github.com/napcs/node-livereload/commit/7245d114fb7df752fd468f979b41a3dc040e3483

**Comment by smhg** [comment]
Thanks a lot! Seems to work well, nice!
