### ISSUE TITLE
Version 0.8.0 does not reload

### ISSUE THREAD

**Issue by dozamen** [napcs/node-livereload#135]
## What version of Livereload are you using?
0.8.0, 0.8.1

## What OS are you using?
Ubuntu 18.04.3

## What web browser are you using? (Browser name and specific version please)
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
(tested also on Firefox 69)

## Expected result
Expected page to reload.

## Actual result
No reloading

## Steps to reproduce issue 
Livereload for version `0.8.0` and `0.8.1` does not work. I assume that it is a problem of my system but I could not find an any clue how to solve it.

Please download attached project ([testlr.tar.gz](https://github.com/napcs/node-livereload/files/3649577/testlr.tar.gz)) and run:
```
tar -xzf testlr.tar.gz
cd testlr
npm i
npm run watch
```
When I modify the `site/index.html` I can see in the terminal that the livereload process see the change but the browser receives no websocket message about it. There are no errors in the Dev Tools console.

Log in the terminal:
```
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.0.0","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://127.0.0.1:8080/"}

Reloading: <base-path>/testlr/site/index.html
```
Log from DevTools:
![ws-log](https://user-images.githubusercontent.com/26811945/65552032-9f3dfd00-df23-11e9-8914-e68fc799c22f.png)

When I down grade to `livereload@0.7.0` all works as expected and page reloads
```
npm i --save livereload@0.7.0
npm run watch
```

## Why is this important?
Reloading is very useful ;)

**Comment by sirolf** [comment]
Same problem but only with 0.8.1 (0.8.0 works for me)

**Comment by sashee** [comment]
0.8.0 works for me also, 0.8.1 does not

**Comment by napcs** [comment]
@sashee @sirolf @dozamen are you using the browser plugin or are you using the embedded javascript that you add to the page?

**Comment by sirolf** [comment]
We are using the embedded javascript.

Op do 3 okt. 2019 03:49 schreef Brian Hogan <notifications@github.com>:

**Comment by sashee** [comment]
I'm using the browser plugin. I've also checked the network tab and no messages are coming through the WS channel after the handshake.

**Comment by jeka-kiselyov** [comment]
Hi there.

Looks that wss.clients was array some versions ago - https://github.com/websockets/ws/blob/v1.x/lib/WebSocketServer.js#L99
And now it's Set and it breaks everything - https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L105

Fixed in PR above.

**Comment by napcs** [comment]
Merged. Closing this issue. 0.8.2 will be released shortly. Thanks for your patience.
