### ISSUE TITLE
update process client extension

### ISSUE THREAD

**Issue by smhg** [napcs/node-livereload#139]
What are your thoughts on a process for updating the client extension?
There were some releases in the meanwhile and it is tedious to bother you with a new release for each of them.

**Comment by napcs** [comment]
@smhg Is there a way you can automate a PR against this repo when you do a release? At least then it's not a manual step for you.

**Comment by smhg** [comment]
Naive question: why can't it be a regular dependency?
Where [this line](https://github.com/napcs/node-livereload/blob/ef459711129675d810308acf0a1aeb835c580415/lib/livereload.coffee#L193) would serve it from node_modules.

**Comment by napcs** [comment]
Go ahead and make a pr that does this and I'll test it out.

**Comment by napcs** [comment]
Closed by #140

**Comment by smhg** [comment]
Thank you! Would you be able to publish this to npm? It would mainly reinstate IE11 support (which is annoying people).

**Comment by napcs** [comment]
@smhg I'm trying to get #141 addressed at the same time before I do a release.
