### ISSUE TITLE
Update chokidar

### ISSUE THREAD

**Issue by daveisfera** [napcs/node-livereload#141]
## What version of Livereload are you using?
0.8.2

## What OS are you using?
macOS 10.14.6

## What web browser are you using? (Browser name and specific version please)
Chrome 78.0.3904.108

## Expected result
`chokidar` 3.x used

## Actual result
`chokidar` 2.x used

## Steps to reproduce issue 

1. Install `livereload`
2. `yarn why chokidar`

## Why is this important?
`chokidar` 3.x has [significant performance improvements](https://github.com/paulmillr/chokidar/releases/tag/3.0.0)

Another option would be to use the [native watch support in node](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_watch_filename_options_listener)

**Comment by napcs** [comment]
We won't be using `fs.watch` because

> The fs.watch API is not 100% consistent across platforms, and is unavailable in some situations.

I'll look at updates to chokidar.

**Comment by daveisfera** [comment]
Reading through the documentation for `fs.watch` a bit more, I think that not using it is the right call, but updating to 3.x would be great!

**Comment by YouWillBe** [comment]
https://github.com/fsevents/fsevents/issues/291

**Comment by napcs** [comment]
Fixed by https://github.com/napcs/node-livereload/commit/476b1b8a5aeac98c987e8a33ac9fc3e418002ed3
