### ISSUE TITLE
client can't be found

### ISSUE THREAD

**Issue by smhg** [napcs/node-livereload#143]
I'm sorry but I made a mistake in my attempt to serve the client from node_modules.

In a project that depends on node-livereload, npm can flatten the dependency tree and put livereload-js on a different level (one up in my case). So it can't be found currently.

One solution I can think of is adding it to the build step. That is fairly straightforward.

But I want to ask you this beforehand: would you be open to let me convert this project to plain JS? It is hard to contribute (I know close to no coffeescript). And it is very easy with [decaffeinate](https://github.com/decaffeinate/decaffeinate).
One of the reasons I ask is because there are currently a few tiny issues which make it hard to jump right in and contribute:

- mocha tests output a deprecation warning
- tests fail the first time you run them after git clone
- the package-lock file is not up-to-date
- running tests creates a git diff
- dependency on Cake (npm can easily take over the buildstep)

Each of them straightforward to solve, but a bit 'frustrating' with coffeescript in your way.

What are your thoughts?

**Comment by napcs** [comment]
Fixed by #142

**Comment by napcs** [comment]
@smhg I'm already working on a pure JS version which I hope will end up being v1.0. Thanks for the offer. I'm going to take a look at the contribution blockers you mentioned as well and see what I can do about those.

**Comment by smhg** [comment]
@napcs Thanks for the new release!
These were only suggestions. Just shout if you need help.
