### ISSUE TITLE
Failling to load livereload dependency

### ISSUE THREAD

**Issue by gingerchris** [napcs/node-livereload#144]
## What version of Livereload are you using?

0.9.0

## What OS are you using?

MacOS 10.14.6

Also:
node v12.3.1
npm v6.13.7

## What web browser are you using? (Browser name and specific version please)
Any

## Expected result

The server should serve `livereload.js`

## Actual result

The server crashes when trying to load `livereload.js` with the following error:

```
internal/fs/utils.js:461
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/chrisdowling/Dev/test/node_modules/livereload/lib/../node_modules/livereload-js/dist/livereload.js'
    at Object.openSync (fs.js:431:3)
    at Object.readFileSync (fs.js:333:35)
    at Server.requestHandler (/Users/chrisdowling/Dev/test/node_modules/livereload/lib/livereload.js:232:27)
    at Server.emit (events.js:200:13)
    at parserOnIncoming (_http_server.js:709:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/chrisdowling/Dev/test/node_modules/livereload/lib/../node_modules/livereload-js/dist/livereload.js'
}
```

## Steps to reproduce issue 

Create a new project with basic livereload setup:

`index.js`:
```
var connect = require('connect');
var static = require('serve-static');

var server = connect();

server.use(static(__dirname + '/public'));

server.listen(3000);

var livereload = require('livereload');
var lrserver = livereload.createServer();
lrserver.watch(__dirname + '/public');
```

`index.html`:
```
<!DOCTYPE html>
<html>
  <body>
    <p>Hello, world!</p>
  </body>
  <script>
    document.write(
      '<script src="http://' +
        (location.host || 'localhost').split(':')[0] +
        ':35729/livereload.js?snipver=1"></' +
        'script>'
    );
  </script>
</html>
```
Run `node index.js` in terminal and attempt to access `http://localhost:3000`

Observe the server has crashed.

It looks like when the project depends on other packages that themselves depend on `livereload-js`, npm installs `livereload-js` to the root `node_modules` directory and not to `node_modules/livereload/node_modules`, causing [this path to not resolve](https://github.com/napcs/node-livereload/blob/master/lib/livereload.coffee#L193).

## Why is this important?

Its pretty fundamental to livereload functionality.

**Comment by napcs** [comment]
fixed by #142
