### ISSUE TITLE
Feature request: Enable error message or logging levels to trace errors to stdout if things dont work.

### ISSUE THREAD

**Issue by laurencefass** [napcs/node-livereload#149]
What version of Livereload are you using?
0.9.1

What OS are you using?
debian

What web browser are you using? (Browser name and specific version please)
chrome Version 84.0.4147.135

Provide error output or logging levels to trace errors if things dont work.

## Actual result
My site is currently hanging waiting for GET livereload and only loads if i stop livereload. There is no output suggesting a problem. I have raised this as a separate issue but a more general problem is the lack of any output of error logging which may apply in other cases.
 
## **Steps** to reproduce issue
start livereload on the server
try to fetch mydomain.com/livereload/livereload.js?snipver=1
observe no response and no server log messages from livereload

**Comment by napcs** [comment]
Does the `-d` switch provide any insight? We've had debugging messages for quite some time now.

**Comment by laurencefass** [comment]
running with 

`livereload . -w 1000 -d -u true -e 'css,js,scss,html,twig'`

doesnt show any output problems. however i have things working so closing issue.
