### ISSUE TITLE
Support proxied socket URL connections when running livereload from the command line. i.e. allow definition of a public socket URL.

### ISSUE THREAD

**Issue by laurencefass** [napcs/node-livereload#150]
What version of Livereload are you using?
0.9.1

What OS are you using?
debian

What web browser are you using? (Browser name and specific version please)
chrome Version 84.0.4147.135

## Expected result
I am running livereload behind a proxy and and I want to be able to name my development URL which I am proxying to localhost:<port> on the server. This appears possible by creating my own app using  "originalPath" property but there is no such documented equivalent when starting from the command line.  Do I need to write my own server to achieve this or is it possible from the command line but just not documented?

I have modified the script to remove the port the a proxy URI

```
  <script>
    let script = '<script src="https://' + (location.host || 'localhost').split(':')[0] +
    '/livereload/livereload.js?snipver=1"></' + 'script>';
    document.write(script);
    console.log(script);
  </script>
```
but the livereload.js is failing when it runs as its calling back to an unexposed port.

I need to set the socket URL of livereload to match my proxy. 

## Quick patch and test

I can fix the problem by adding a breakpoint to the LOC above and manually removing the port from the uri before execution to match my proxied address. Livereload then works until a page reload. 

## Actual result

Code fails on line 2169 in the browser livereload.js.

_createClass(Connector, [{ 

...
2169:  this.socket = new this.WebSocket(this._uri);
... 
);

test fail: uri = wss://drupal894.syntapse.co.uk:35729/livereload

should be wss://drupal894.syntapse.co.uk/livereload

## Steps to reproduce issue 

running livereload with

```
livereload . -w 1000 -d -u true -e 'css,js,scss,html,twig'
```

(note this doesnt allow the configuration of a proxied socket URL so the client is calling back to the port).

configure nginx proxy as follows:

```
  #  proxy request for livereload.js on page load
  location ~ ^(\/livereload)(.+) {
    proxy_pass http://0.0.0.0:35729$2;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # proxy the socket connection direct to port 
  location ~ ^(\/livereload)$ {
    proxy_pass http://0.0.0.0:35729;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
 }

```
## Why is this important?
to be able to test this across a proxied connection to enable containerised parallel development on a single machine.

I want it to demonstrate livereload across a range of apps in multiple containers without exposing a single port or configuring multiple ports across apps.

**Comment by napcs** [comment]
@laurencefass This looks easy enough to expose this option. Adding it to the backlog.

**Comment by napcs** [comment]
@laurencefass Version 0.9.2 is out which adds CLI support for the `-op` or `--originalPath` option.
