### ISSUE TITLE
javascript code auto injected in HTML page

### ISSUE THREAD

**Issue by IbrahimBond** [napcs/node-livereload#151]
## What version of Livereload are you using?
latest version

## What OS are you using?
ubuntu 18.04

## What web browser are you using? (Browser name and specific version please)
firefox, chrome 
## Expected result
see one javascript code in the html when i click inspect element in the browser(the code in the readme "Add code to page")

## Actual result
there are two pieces of javascript code. the one from the readme and another injected one that looks like this:

```
 <html><head>
</head>
<body>

<script>
  document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
  ':35729/livereload.js?snipver=1"></' + 'script>')
</script><script src="http://xxx.xxx.xx.xxx:35729/livereload.js?snipver=1"></script>

<script src="//xxx.xxx.xx.xxx:35729/livereload.js?snipver=1" async="" defer=""></script>
</body></html>

```

if i remove the code in the read me from the HTML file i see only one javascript code, which i dont know how gets injected and unlike the one above has "http before the two slashes" like this: 

```
<html><head>
</head>
<body>

<script src="http//xxx.xxx.xx.xxx:35729/livereload.js?snipver=1" async="" defer=""></script>
</body></html>

```
## Steps to reproduce issue 

it is not really causing me an issue, as everything is working, but i need to understand what is going on 

i also have two other questions"
1 - does it make sense to use this outside of development. where i expose the server publicly and i want to refresh image in the client browser upon change? 

2- is it possible to refresh a certain page? such as  http://xxx.xxx.xx.xxx/page?

**Comment by napcs** [comment]
@IbrahimBond  The extra code you're seeing is from the browser extension. If you use the browser extension then you do not need to add HTML code to your project. You have to pick the method you wish to use - either add the JS code to your HTML files, or use the browser extension.

To answer your questions:

1. This is a development tool. If your intention is to refresh a page, a basic <meta refresh> tag will do that, or a basic setTimeout loop in JavaScript would work much better and be less complex.

2. If you're only interested in refreshing a specific page, add the js to that page only.

**Comment by IbrahimBond** [comment]
> @IbrahimBond The extra code you're seeing is from the browser extension. If you use the browser extension then you do not need to add HTML code to your project. You have to pick the method you wish to use - either add the JS code to your HTML files, or use the browser extension.

i understand that the extension injects the code automatically, but i am confused because i did not install the extension in any of the browsers. 

> To answer your questions:
> 
> 1. This is a development tool. If your intention is to refresh a page, a basic  tag will do that, or a basic setTimeout loop in JavaScript would work much better and be less complex.
> 2. If you're only interested in refreshing a specific page, add the js to that page only.

thanks of the answers, i will consider them!

**Comment by napcs** [comment]
> i understand that the extension injects the code automatically, but i am confused because i did not install the extension in any of the browsers.

Perhaps you are using a library that injects this behavior itself. I see this with many web frameworks that include their own libereload functionality. 

The livereload CLI tool does not automatically inject that fragment into web pages, so this is not an issue with this library.
