### ISSUE TITLE
livereload --debug disables file watcher

### ISSUE THREAD

**Issue by dotnetCarpenter** [napcs/node-livereload#152]
## What version of Livereload are you using?

livereload: 0.9.1
npm: 6.14.8
node: v14.13.0

## What OS are you using?

Windows 10 WSL 2
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

## What web browser are you using? (Browser name and specific version please)

Windows 10
Opera Version:72.0.3815.186

## Expected result

`livereload` should detect changes in watched files.

## Actual result

`livereload` does **not** detect any changes.

<details>
<summary>Here is the output while I tried to trigger reload by changing <code>mathilde.css</code> and refreshing the browser:</summary>

```
Serving HTTP on 0.0.0.0 port 9000 (http://0.0.0.0:9000/) ...
LiveReload is waiting for a browser to connect...

Protocol version: 7
Exclusions: /\.git\//,/\.svn\//,/\.hg\//
Extensions: html,css,js,png,gif,jpg,php,php5,py,rb,erb,coffee
Polling: false


Starting LiveReload v0.9.1 for /home/dotnet/projects/firefund/firefund-lfs/design/gradient_donut/--debug on port 35729.
Watching /home/dotnet/projects/firefund/firefund-lfs/design/gradient_donut/--debug...

127.0.0.1 - - [10/Nov/2020 16:55:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Nov/2020 16:55:32] "GET /mathilde.css HTTP/1.1" 304 -
127.0.0.1 - - [10/Nov/2020 16:55:32] "GET /assets/fonts/roboto-regular.woff2 HTTP/1.1" 304 -
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.3.1","snipver":1}

Client requested handshake...


Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://localhost:9000/"}

Server received client data. Not sending response.

127.0.0.1 - - [10/Nov/2020 16:55:32] "GET /donut.png HTTP/1.1" 304 -
Client closed connection

127.0.0.1 - - [10/Nov/2020 16:56:10] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [10/Nov/2020 16:56:10] "GET /mathilde.css HTTP/1.1" 304 -
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.3.1","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://localhost:9000/"}

Server received client data. Not sending response.

Client closed connection

127.0.0.1 - - [10/Nov/2020 16:56:25] "GET / HTTP/1.1" 304 -
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.3.1","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://localhost:9000/"}

Server received client data. Not sending response.

^C
Keyboard interrupt received, exiting.
./server.sh: line 8: fg: no job control
```

</details>

## Steps to reproduce issue 
Using `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`:

This does **not** work:
`npx livereload --debug & python3 -m http.server 9000 && fg`

This **does** work:
`npx livereload & python3 -m http.server 9000 && fg`

Brief explanation of `fg`: https://stackoverflow.com/a/5553774/205696

## Why is this important?

It appears to be a bug. I have not researched enough to pin down the course but I guess that it has to do with writing to stdout (via the `--debug` flag) and the `&` operator.

>The & operator puts command in the background and free up your terminal.

**Comment by dotnetCarpenter** [comment]
I actually have my repo for you, in case  you want that as an easier way to reproduce.
https://github.com/Firefund/firefund-lfs/tree/master/design/gradient_donut

**Comment by napcs** [comment]
Hi @dotnetCarpenter. Sorry for the delayed reply. 

This is certainly a strange one.  Before we dig too deep, can we remove `npx` from the mix here? Install livereload globally please, with `npm install -g livereload` and run it directly. Since `npx` is a wrapper, I suspect there's something else going on here.

**Comment by dotnetCarpenter** [comment]
I get the exact same result when I run `livereload --debug` directly from the terminal.

I edited `index.html` and **without** the `--debug` flag it worked flawlessly (reloaded) but not at all with the `--debug` flag.

**Comment by napcs** [comment]
@dotnetCarpenter I think I know what's going on. When livereload writes to STDOUT your shell may be halting its execution. There are some shells that default to this behavior.

Try issuing this command first:

```
stty -tostop
```

This instructs the shell to continue processing even if the program writes to STDOUT.

**Comment by dotnetCarpenter** [comment]
It doesn't seem to make any difference. I am using Windows Terminal Version: 1.4.3243.0.

**But** I notice that the `path` ends in `"--debug"` when I add the `--debug` flag.

```
Starting LiveReload v0.9.1 for /home/dotnet/projects/firefund/firefund-lfs/design/gradient_donut/--debug on port 35729.
Watching /home/dotnet/projects/firefund/firefund-lfs/design/gradient_donut/--debug...
```
_**/home/dotnet/projects/firefund/firefund-lfs/design/gradient_donut/--debug**_
```coffee
console.log "Starting LiveReload v#{version} for #{path} on port #{port}."
```

That might explain why [server.watch(path)](https://github.com/napcs/node-livereload/blob/main/lib/command.coffee#L99) is not working.

**Comment by napcs** [comment]
@dotnetCarpenter Oops.  I didn't catch this. This is actually pointed out in  the README file. When you use the options, you have to specify the path.

```
livereload . --debug
```

It's because of the way the options are parsed and it goes back to before I took this project over, and I always forget about this. 

I just made a backwards compatible fix coming for this that eliminates that issue by properly parsing out the path option, but that's what's happening to you.

If that addresses this, please close this. I'll tag this issue when the new release is out. So sorry for the trouble!!

**Comment by dotnetCarpenter** [comment]
This works great! I didn't see _Specify the path when using the options._ in the README...

I also can not see your commit for the fix but I've changed my bash script. I hope you commit your fix for the next release. I might not be the only one who does not closely read the README.

Thank you for all your support and for maintaining livereload!

Happy new year!

**Comment by napcs** [comment]
@dotnetCarpenter yea the next release will definitely have the options fix in it; it's been bugging me for far too long and I finally found the time to investigate what the heck was going on. I've not pushed the branch to GH yet.

**Comment by dotnetCarpenter** [comment]
Hi @napcs, is there any way I can speed this along? I got bitten by this bug again, just now.

I hope you are good and I don't mean to stress you. Just curious if I can help?

**Comment by napcs** [comment]
@dotnetCarpenter thanks for the ping. I've already got a branch with the updated code. I'm trying to resolve #147 and #148 before I push the next version though.

**Comment by napcs** [comment]
@dotnetCarpenter Version 0.9.2 is out and it has this fix added. Thanks for your patience.
