### ISSUE TITLE
Feature request: support refreshing when an endpoint returns 200

### ISSUE THREAD

**Issue by damusix** [napcs/node-livereload#153]
## What version of Livereload are you using?
0.9.1

## What OS are you using?
MacOS

## Details

I often use livereload along with `nodemon` to cause refreshes on server / client whenever a backend or frontend file changes.
My particular use case: I have a `hapi` server that serves static files and handlebars-rendered HTML. Webpack compiles SASS and minifies a JS file. When I change a JS file, nodemon refreshes Hapi. When I change CSS or `dist/app.js`, livereload refreshes the browser.

The issue is that a `delay` option will vary computer to computer, and needs to increase as the app restart time increases from added complexity. Instead, could there maybe be an option to livereload after, say, `http://localhost:4000/` returns 200? EG:

`livereload --endpoint "http://localhost:4000/" --backoff 1000 [...options]`

**Comment by napcs** [comment]
I think this is getting far too out of scope for what this program is designed to do, so I think I'm going to decline this.

You can integrate livereload into your dev server if you want more specific behavior.

Alternatively, there are tools higher-up the stack that provide what you're looking to do, like browser-sync.
