### ISSUE TITLE
Command line for multiple path seems to be broken in 0.9.2

### ISSUE THREAD

**Issue by jeremychone** [napcs/node-livereload#154]
System: Mac, Chrome (but not a client issue), node.js 14
version with the issue: 0.9.2
version with NO issue: 0.9.1

## Steps to reproduce

- Two folder `css/` and `svg/`
- Using the command line
  - `./node_modules/.bin/livereload "dist/, svg/" --extraExts svg -w 500 -d`
- Edit a `dist/some.css` file

### Actual

with `0.9.2`, nothing happen, the livereload terminal does not print anything, which seems to mean it did not watch the folder, and browser does not get updated.

### Expected

With `0.9.1`, changing any `.js` or `.css` or `.svg` in any of those directories console.log the change notification in the terminal and reloaded the browser correctly. 

## Workaround

Rollback to `0.9.1`

**Comment by napcs** [comment]
@jeremychone super sorry about this. I broke an assignment operator when resolving a path. New release coming soon.

**Comment by jeremychone** [comment]
Confirming that 0.9.3 fixed this issue. Thanks!
