### ISSUE TITLE
Cannot use multiple node-livereload servers on one page

### ISSUE THREAD

**Issue by raihle** [napcs/node-livereload#163]
## What version of Livereload are you using?

0.9.3

## What OS are you using?

Windows 10 Enterprise 20H2

## What web browser are you using? (Browser name and specific version please)

Firefox 100.0.2
Chrome 102.0.5005.63

## Expected result

Two different JavaScript modules, each instrumented by their own node-livereload instance, should both be able to reload the page.

## Actual result

The page is stuck waiting for one specific module to change. After that module has changed and the page reloads, it seems the page will wait for the other module to change, and switch back and forth. The switching may be inconsistent (race condition?), I have not tested thoroughly.

## Steps to reproduce issue 

I am injecting two nearly identical scripts on my page, differing only in the element ID and port number:
```js
(function(l, r) { if (!l || l.getElementById('livereloadscript-xxx')) return; r = l.createElement('script'); r.async = 1; r.src = '//' + (self.location.host || 'localhost').split(':')[0] + ':35736/livereload.js?snipver=1'; r.id = 'livereloadscript-xxx'; l.getElementsByTagName('head')[0].appendChild(r) })(self.document);
==>
<script async="" src="//localhost:35736/livereload.js?snipver=1" id="livereloadscript-xxx"></script>
```

```js
(function(l, r) { if (!l || l.getElementById('livereloadscript-yyy')) return; r = l.createElement('script'); r.async = 1; r.src = '//' + (self.location.host || 'localhost').split(':')[0] + ':35733/livereload.js?snipver=1'; r.id = 'livereloadscript-yyy'; l.getElementsByTagName('head')[0].appendChild(r) })(self.document);
==>
<script async="" src="//localhost:35733/livereload.js?snipver=1" id="livereloadscript-yyy"></script>
```

I'm starting a server on each of the respective ports, watching for changes in two different sub-projects. 

In my browser, I can see two websocket connections being opened to one of the servers, and no connections being opened to the other. Changes that are being watched by the other server (obviously) have no effect on the page. Changes that are being watched by the connected-to server cause the page to reload as expected. After such a reload, my browser (seemingly consistently) connects to the other server.

This seems to happening because the livereload script extracts port (etc.) information from a script tag on the page - not necessarily _its own_ script tag, but the _first_ script tag that fetched a `livereload.js` script. Therefore both instances of the script end up connecting to the same server, even though they were initially served by different servers. This extracted port information seems to take precedence over any configuration that can be provided.

## Why is this important?

This appears to be a bug, or at least unexpected behavior.

The two sub-projects are meant to be runtime dependencies of the page I'm working on, which is why they have separate build processes. I don't see any way that outputs from separate builds could be watched simultaneously without addressing this issue.

**Comment by napcs** [comment]
@raihle Thanks for such a detailed report. Unfortunately I don't think I can help here.

This project is not responsible for the behavior of the livereload script. It's packaged as a dependency for convenience only. This project is only for the backend websocket piece.

 I have not seen a case where you would inject more than one of these scripts on the same page, but this project only deals with handling back-end requests.

I recommend you check out the livereload js client script, but I suspect this is by design. I've never seen a use case like yours. 

Sorry I can't help more here.
