### ISSUE TITLE
this.reloader NPE on IE8

### ISSUE THREAD

**Issue by jareware** [napcs/node-livereload#30]
I know this won't be a huge priority to fix, but at least on IE8 (maybe later ones as well) including the client-side `livereload.js` triggers the following error on line 961:

```
'this.reloader' is null or not an object
```

Might just add a check before accessing that property, so old & buggy browser will fail quietly (e.g. just no livereload) instead of making noise.

**Comment by napcs** [comment]
The client-side LiveReload isn't something I plan to change. That's an upstream change. And I can't imagine with IE8 it'll get fixed anytime soon.
