### ISSUE TITLE
Alternative stylesheet

### ISSUE THREAD

**Issue by stevschm** [napcs/node-livereload#33]
Livereload doesn't change css on this: <link rel="alternate stylesheet"

**Comment by napcs** [comment]
LiveReload's JS client doesn't appear to support that for this protocol. That's a client-side issue and out of scope.

**Comment by thescientist13** [comment]
Fwiw, I have CSS files I load via `<style>` tags in my _index.html_ files and although watching and refreshing for HTML, CSS, JS, and Markdown files worked great, only on _.css_ files would I get an error in the terminal and browser console when the browser reloaded, where in the **livereload** script was being appended to the CSS file's `<style>` tag.

For example given an _index.html_ like this...
```html
...

<head>
  <script type="module" src="../components/header/header.js"></script>
  <script type="module" src="../components/footer/footer.js"></script>

  <link rel="stylesheet" href="../styles/theme.css"></link>
  <link rel="stylesheet" href="../styles/home.css"></link>

 <script src="http://localhost:35729/livereload.js?snipver=1"></script>
</head>

...
```

and the following configuration
```js
const liveReloadServer = livereload.createServer({
  exts: ['html', 'css', 'js', 'md']
});
```

was seeing this
```sh
 Error: ENOENT: no such file or directory, open '/path/to/repo/www/styles/theme.css?livereload=1600296112330'
```

![Screen Shot 2020-09-16 at 6 31 39 PM](https://user-images.githubusercontent.com/895923/93399701-1a42a680-f84c-11ea-901f-28a8b975db2c.png)

----

However, using [`applyCSSLive`](https://github.com/napcs/node-livereload#server-api) set to `false` fixed the issue for me.  🎉 
```js
const liveReloadServer = livereload.createServer({
  exts: ['html', 'css', 'js', 'md'],
  applyCSSLive: false
});
```

Hope that helps!
