### ISSUE TITLE
Console output verbosity

### ISSUE THREAD

**Issue by Francisc** [napcs/node-livereload#44]
Hello,

Is there any way to turn off console verbosity?
Anytime a file refreshes, `livereload` prints out 5 lines in the console (including newlines).

```
Refresh: path/to/file

Browser connected.

Browser URL: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.2.1","ext":"Chrome","extver":"2.1.0"}

```

That's not very helpful and makes the console unreadable if run in parallel with other tasks, such as a watch job.

Is there a CLI option to turn that off?

**Comment by napcs** [comment]
@Francisc It's coming - see #36

**Comment by Francisc** [comment]
Thank you.
