### ISSUE TITLE
Add Exclusions to command line option

### ISSUE THREAD

**Issue by napcs** [napcs/node-livereload#46]
We should add exclusions to command line options.

See #43

**Comment by bdaniel7** [comment]
Very good idea. I tried to add new extensions to monitor and it was possible only within a script. Then I wanted to increase the monitor interval but it's available only in the command line arguments.

**Comment by travstone** [comment]
I'd like to see this as well; when I use the CLI version via a script in Webpack, the page periodically reloads by itself because of a github process (I think)... I used the -d flag and here's a sample:

`Refresh C:\path\to\my\project\.git\FETCH_HEAD`
`Client closed connection`
`Browser connected`
`Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.2.2","ext":"Chrome","extver":"2.1.0"}`

This makes it hard to work in devtools (chrome), as any changes I make there run the risk of getting wiped out unexpectedly due to page reload.

**Comment by napcs** [comment]
@travstone this is a really easy PR to make - I'm really hoping someone wants to step up and submit it. Wanna go for it?

**Comment by napcs** [comment]
@travstone wait - your issue may be a separate issue. We have code that should already ignore .git stuff by default. Can you make a new issue please?

**Comment by travstone** [comment]
Sorry! Just re-checked this, and it was my own sloppy code. Am using parallelshell to run livereload with some other watchers on windows, and didn't properly quote/escape things.

Will consider the PR- I know so little about this repo I'm not sure I can be helpful just yet... thanks for the response though!

**Comment by napcs** [comment]
@travstone I'm happy to help you through it if you want to make a contribution :)

**Comment by travstone** [comment]
Ok, might take you up on that- I want exclusions for CLI/script now... : )

**Comment by dubeg** [comment]
Shouldn't this issue be closed? @napcs, didn't you add this in [2015](https://github.com/napcs/node-livereload/blob/master/lib/command.coffee#L28)? The only thing missing is to add a line about it in README > _Command lines options_.

**Comment by travstone** [comment]
Perhaps I am doing it wrong, but '-exclusions' throws an error for me ("Unknown option: -exclusions"), while '-x' does not throw error, but does not appear to exclude directories- I can't even get it to exclude a particular file by name. Just to be clear, in my case livereload is being called from a 'script' in my package.json via the command line.

**Comment by dubeg** [comment]
@travstone The long name takes two dashes. Ex: `--exclusions` . 

As for the exclusions not working, it might have something to do with the current working directory being different in a child script. Try to resolve your relative paths before giving them to livereload via the command line.

**Comment by napcs** [comment]
@dubeg LOL you're right - this was done - I got this mixed up with the extensions. Closing.

**Comment by travstone** [comment]
Awesome, thank you both. The exclusions were working, I just didn't have them specified correctly. Note for future, it appears that one may not use spaces after commas on the exclusions string... otherwise it only works for the first path... thanks again!

**Comment by napcs** [comment]
Just a note that the upcoming 0.6.4 will fix the issues with spaces. :)
