### ISSUE TITLE
Server not serving pages. No error message shown.

### ISSUE THREAD

**Issue by edoardoo** [napcs/node-livereload#48]
Hi, 
I'm trying to use this package, but whenever I try to use it, the browser will just keep stuck on loading the page.
I tried with the basic example: 
1- installing livereload locally
2- creating a node `server.js` file
3- writing down the lines you wrote to create the basic server
4- adding in the *public* folder with `index.html` and the script you wrote on the welcome page.
5- going to `http://localhost:35729` or `http://localhost:35729/index.html`

I've also tried using it globally with `livereload public/` but so far it didn't work. 

Thank you for your work.

**Comment by Davideb94** [comment]
+1

**Comment by napcs** [comment]
35729 is the websocket port.

Try port 3000. That's what the example server listens on in the README. :)

**Comment by napcs** [comment]
Connect made some changes that broke the example in our README so I updated it in 48b0af0bd

**Comment by pdavid0** [comment]
I still have this issue

    var server = livereload.createServer({port:3000});//http.createServer(app);
    server.watch(__dirname);

**Comment by napcs** [comment]
@pdavid0 

OS? Node version? Repository that can reproduce error?
