### ISSUE TITLE
livereload doesn't trigger reload on change

### ISSUE THREAD

**Issue by dotnetCarpenter** [napcs/node-livereload#51]
I've created a test case here: https://github.com/dotnetCarpenter/livereload-test

I run [ecstatic](/jfhbrook/node-ecstatic) as web server with root in `root/` and livereload watching `root/css/`
To run the test case locally you can just clone the repo and do `npm i` and then `npm run testlivereload`. Open your browser at localhost:8000 and you should see a message in the console:
```
Starting LiveReload v0.4.0 for [...]/livereload-test/root/css on port 35729.
Browser connected.
Browser URL: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","snipver":"1"}
```
In the browser devtools I see that http://localhost:35729/livereload.js?snipver=1 is loaded but when I change the content in `a.css` the page does not get reloaded.

As a side note, running livereload with `livereload root/css -d -e css` fails with `Unknown option: -e
Try --help`. `-e | --exts` is documented in the [livereload README](https://github.com/napcs/node-livereload#command-line-options)

**Comment by dotnetCarpenter** [comment]
I just ran the same test case with livereload version 0.3.7 and it worked perfectly. So it's a regression since 0.3.7.

**Comment by napcs** [comment]
Cloned your repository and followed your instructions.  Worked just fine for me the first try.
Using OSX, Node 4.1.1

Cannot reproduce. Feel free to reopen if you can provide more information.

**Comment by ivw** [comment]
I ran into the same problem on Windows, and also ended up using 0.3.7.
Maybe it's only broken on Windows.

**Comment by dotnetCarpenter** [comment]
@ivw

**Comment by napcs** [comment]
@ivw @dotnetCarpenter in version 0.4.0 we switched the file watcher to Chokidar  <https://github.com/paulmillr/chokidar> so we could avoid interval-based polling. Chokidar is used by Gulp and other tools for file watching. Are there any more bits of info you can give me such as your version of Windows and version of Node that you're using?

**Comment by dotnetCarpenter** [comment]
@ivw actually you have to type `npm run live` in one console and open another console and type `npm run server` because running tasks in the Windows console is not supported. I just tried on Windows 7 with livereload 0.3.7 and it worked in that order.

I then tried with livereload 0.4.0 but had issues with getting `chokidar`'s dependencies to build. But after reading [a comment from MS about their new C++ build tool](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245) and installing Windows 8.1 SDK (even though I'm on Windows 7) I got things working with livereload 0.4.0.

**Comment by dotnetCarpenter** [comment]
@napcs In my case the issue is only happening on Mac (haven't tested linux though). I'm on Windows right now and it will take a few days before I'm on Mac again.

**Comment by ivw** [comment]
I just did a fresh `npm install` with livereload 0.4.0 and now it works for me too. I didn't change anything else.

Maybe one of livereload's dependencies has updated which fixed it, I don't know what else it could have been :)

**Comment by napcs** [comment]
@dotnetCarpenter again, what version of OSX and what version of Node didn't work for you? This information would be helpful. If you're having problems, chances are that others are as well.

**Comment by dotnetCarpenter** [comment]
@napcs 
OSX Yosemite 10.10.5
node -v v5.0.0
npm -v 3.3.9
livereload -v 0.4.0
