### ISSUE TITLE
Delay before refresh ?

### ISSUE THREAD

**Issue by daslicht** [napcs/node-livereload#53]
Is there a way to add a delay before the browser is refreshed ?

**Comment by napcs** [comment]
Not currently. What's the use case?

**Comment by daslicht** [comment]
Lets assume we also have something like forever running which restarts the server on file change.
If there is no delay in most cases the server has not been restarted before we reload the page.

**Comment by napcs** [comment]
I think that's out of scope for this project, sorry. This is designed to be really simple. If you're looking to use other processes alongside a livereloader, you may want to use something that's designed to integrate with that process.

**Comment by daslicht** [comment]
It is out of scope ? That option is needed for any node project !

**Comment by napcs** [comment]
@daslicht It may be possible to add a delay, but that's going to be pretty obnoxious. #56 covers this a little bit. 

But if you're using another watcher to restart the server, then you probably should consider a different tool than this one. Grunt and Gulp both have plugins that watch for changes and support livereloading your browser. If you combine what you're doing to restart the server with one of those task runners, I think you'll have a better experience.

Every feature request is more code I have to maintain. If someone wants to contribute a patch with tests, I'll be happy to include it.

**Comment by daslicht** [comment]
Using grunt or gulp makes things even worse. ;) 
But never mind I have split the server watch from the client and anything is OK
