### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by zuber303** [napcs/node-livereload#55]
Hi. I have installed livereload in nodejs and now I'm straggling with this code: 
Where shell I add it?
<addr>livereload = require('livereload');
server = livereload.createServer();
server.watch(__dirname + "/public");<addr>

Can you explain please.

**Comment by ismaail** [comment]
Create a file `livereload.js` or whatever name you want.

In this file, put this code:

```
livereload = require('livereload');
server = livereload.createServer();
server.watch(__dirname + "/public");
```

Finally run this file with Node:

```
node livereload.js
```

**Comment by zuber303** [comment]
My html file:
```html
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="style.css">
    <script>
        document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
                ':63342/livereload.js?snipver=1"></' + 'script>')
    </script>
    <script src="http://maps.google.com/maps/api/js?libraries=geometry" type="text/javascript"></script>

</head>
<body>
<div id="map" style="width: 1200px; height: 900px; border: 1px solid black; background: black;">

</div>
<input type="button" id="draw" value="show">

<script src="es6-compiled.js"></script>
</body>
</html>'

My livereload.js:

```javascript
livereload = require('livereload');
server = livereload.createServer();
server.watch(__dirname + "/public");
```
I installed livereload by npm but it doesn't work. I firebug console i have this error:
"NetworkError: 404 Not Found - http://localhost:63342/livereload.js?snipver=1".

livereload.js file is in the same catalogue with html file. Is it correct? 

Thank you

**Comment by ismaail** [comment]
in html document, try line:

```
<script src="http://localhost:35729/livereload.js"></script>
```

**Comment by napcs** [comment]
Does the README.md file not explain this well enough? Perhaps patches are needed.

**Comment by zuber303** [comment]
Maybe README.md file explains well for advanced programmers but I'm a beginner and I would like  more precise code structure explanation which to add to watch specific file. Sorry but I don't find it in readme file.
My file structure is:
-es6
    -node_modules (catalogue)
    -index.html
    -style.css
    -es6-compiled.js

So can you tell me how to configure this mode to watch this 3 files? Thank you.

**Comment by ismaail** [comment]
try this code in `livereload.js` file:

```
var livereload = require('livereload');
var server = livereload.createServer({
    exts: ["html", "css", "js"],
    exclusions: [__dirname + "/es6", __dirname + "/node_modules"]
});

server.watch([
    __dirname
]);
```

- **exts**: specify which file extensions to watch
- **exclusions**: the folders to ignore since server watch the entire directory
- the default port used is 35729 but you can change it if needed

start the livereload with the command
```
node livereload.js
```

---

in the html file add the line

```
<script src="http://localhost:35729/livereload.js"></script>
```

or you can user livereload browser extension http://livereload.com/extensions/

**Comment by zuber303** [comment]
No, didn't help. My localhost works on this address:
http://localhost:63342/es6/index.html, but still I have this error:
"NetworkError: 404 Not Found - http://localhost:63342/livereload.js"

I can't install firefox extension: "You can't install this extension because it's not verified ". What is wrong with this extension?
Thank you

**Comment by ismaail** [comment]
livereload work on its own port (35729)

The extension is not signed, you have to change some Firefox config

In Firefox open the address `about:config` and search for `xpinstall.signatures.required`

change to **false**
