### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by groutch** [napcs/node-livereload#59]
Node version : **5.5.0**
Npm version : **2.13.5**

Hi, 

When I want to install the package livereload `npm install -g livereload`, I have this kind of error : 

> gyp ERR! stack Error: 404 status code downloading 64-bit node.lib

Can you explain ?

Thanks

**Comment by napcs** [comment]
This is not an issue with this library. It's an issue with Node on your system. Perhaps check out

https://github.com/nodejs/node-gyp/issues/724

**Comment by groutch** [comment]
Thanks a lot
