### ISSUE TITLE
Updating many files at the same time causes livereload to reload the files insanely many times

### ISSUE THREAD

**Issue by Elephant-Vessel** [napcs/node-livereload#61]
I have a gulp task that rebuilds all scss files when I'm changing the theme, this is currently resulting in 45 css files being generated in development environment. Problem is that livereload is reloading all files for just one file change, resulting in thousands of requests.
```
module.exports = function (watchDir)
{
    return function ()
    {
        var livereload = require('livereload');
        var server = livereload.createServer({
            originalPath: "http://localhost/mac"
        });
        return server.watch("wwwroot/css/");
    }
}
```

**Comment by Elephant-Vessel** [comment]
I've set debug to true, and can se that node-livereload is actually only trying to refresh the specific files that have changed. Seems like the problem is in the chrome plugin?

**Comment by Elephant-Vessel** [comment]
Using the old firefox add-on, it does the same thing. One file change => reloads everything.

**Comment by Elephant-Vessel** [comment]
I think I've figured it out, the livereload server is sending an event saying that *wwwroot\css\mains\create-task\style\main.css* is updated, but the plugin can not find that files since the web page is in wwwroot itself, so it updates all the stylesheets instead. So I need an option to define the base path so that this server knows to send the event with *css\mains\create-task\style\main.css* instead.

**Comment by Elephant-Vessel** [comment]
I'm playing around with your example by using livereload with connect hoping to be able to modify the event on the way out, but I don't really understand how connect and livereload are supposed to interact.

Are you using connect yourself under the hood? Could you in that case expose the .use method so that we can add our own middleware?

**Comment by Elephant-Vessel** [comment]
I hacked around it like this, I had to unixify the slashes as well:

```
module.exports = function (watchDir) {
    var connect = require('connect');
    var slash = require("slash");

    return function () {

        var livereload = require('livereload');
        server = livereload.createServer({
            debug: true,
            originalPath: "http://localhost/mac",
        });

        var oldFunc = server.filterRefresh;
        server.filterRefresh = function (filePath) {
            filePath = slash(filePath.replace("wwwroot\\", ""));
            oldFunc.call(this, filePath);
        };

        return server.watch("wwwroot/css/");
    }
}
```
This works well except that it emitts a change event three times for some files, but that's good enough for me.

**Comment by napcs** [comment]
This is interesting. I'm trying to wrap my head around the problem a little more. Can you create a simplified repository that exhibits the incorrect behavior?

**Comment by napcs** [comment]
Closing.
