### ISSUE TITLE
ERR_CONNECTION_REFUSED http://localhost:35729/livereload.js?snipver=1

### ISSUE THREAD

**Issue by ericgrosse** [napcs/node-livereload#63]
I added 

`<script>
  document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
  ':35729/livereload.js?snipver=1"></' + 'script>')
</script>`

to the bottom of my page as per the documentation and I get the following error in the Chrome developer console:

`Failed to load resource: net::ERR_CONNECTION_REFUSED http://localhost:35729/livereload.js?snipver=1`

I get this error both when using `file:///` and with http-server running on `localhost:8080`. I've even used `netstat` to check if port 35729 is being used (it's not), and tried changing the port in the script tag, always get the same error.

If instead I run `livereload .` in the root directory of my site, I see

`Starting LiveReload v0.4.1 for C:\Users\eric\workspace\Portfolio Sites\avertourism.com on port 35729.`

in the terminal and nothing else. No error is shown but livereload still doesn't work. If I use Firefox instead of Chrome + the script tag approach, it doesn't show any error but livereload still doesn't work.

I am using Windows 10.

**Comment by napcs** [comment]
I have a theory. Can you try in a folder with no spaces in the pathname and report back?

**Comment by ericgrosse** [comment]
What's weird is that sometimes I get the `ERR_CONNECTION_REFUSED` error, and sometimes I don't, and I don't know how to reproduce it. Whether there are spaces in the pathname or not makes no difference. I did find a working setup however:

Here's a summary of my tests, all run in Chrome:

---

Note: By inline script I mean placing 

`<script> document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>') </script>`

 before the `</body>` tag.

---

- Using `file:///` and inline script: Doesn't work
- Using `http-server` and inline script: Doesn't work
- Using `file:///` and `livereload .`: Doesn't work
- Using `http-server` and `livereload .`: This actually worked!

From this it seems that using either `file:///` instead of a server on `localhost` or the inline script instead of the global `livereload` command cause the livereload setup to fail.

I'm thinking the `file:///` failure has something to do with 

> Only Google Chrome supports viewing file:/// URLS, and you have to specifically enable it.

that's mentioned in the documentation. I'm guessing I don't have it enabled (?) and a quick google search doesn't yield anything. Does the Chrome extension need to be used for `file:///` to work? Is it enabled through some advanced browser setting?

The most irritating thing about this is I distinctly remember having `file:///` + inline script working just a few weeks ago. It sucks to lose that convenience, hope we can figure this out.

**Comment by napcs** [comment]
This HTML file:

```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="stylesheets/style.css">
  </head>
  <body>
    <h1>Hello</h1>
    <script> document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>') </script>
  </body>
</html>

```

works as expected in OSX 10.11 and Windows 10.0 using Chrome 49 with no available updates.

Node v5.3.0 and livereload 0.4.1.

I simply launched

```
$ livereload .
```

and opened the page.  Made some changes with no issues. Page loaded right up.

The official LiveReload plugin has an option to allow local file access, which needs to be enabled under your extensions. But if you're using the script like I am above, that's not necessary.  

If you launch Chrome with the flag `--allow-file-access-from-files` it will allow local files to work. Although in my tests the above code didn't have a problem.

See if you can reproduce using this simple test case. I'm trying to figure out what else might be involved here.

**Comment by napcs** [comment]
Closing after no responses.
