### ISSUE TITLE
Support stream

### ISSUE THREAD

**Issue by tamascsaba** [napcs/node-livereload#64]
I use ```fs.fs.createWriteStream``` to write files and node-livereload reload my files too early.
Chokidar change event fired before stream write is complete.

**Comment by napcs** [comment]
Does the following option help?

`-u` or `--usepolling` to poll for file system changes. Set this to true to successfully watch files over a network.

**Comment by tamascsaba** [comment]
usePolling not good, because you can only setup polling interval, if you use stream you must specify a delay, or an event which wait for successful stream writing end.
https://nodejs.org/api/stream.html#stream_event_end

**Comment by napcs** [comment]
Can you please provide me with a link to a gist or repository that has a failing test case?

**Comment by napcs** [comment]
Closing this. I think #67 might solve this if we get it implemented.
