### ISSUE TITLE
Update ws package

### ISSUE THREAD

**Issue by GreenPioneer** [napcs/node-livereload#66]
`npm i -g nsp`
`nsp check`

│               │ Remote Memory Disclosure                              │
│ Name          │ ws                                                    │
│ Installed     │ 0.8.1                                                 │
│ Vulnerable    │ < 1.0.1                                               │
│ Patched       │ >= 1.0.1                                              │
│ Path          │ meanstackjs@0.3.1 > livereload@0.4.1 > ws@0.8.1       │
│ More Info     │ https://nodesecurity.io/advisories/67                 │

Would you be willing to update that package?

**Comment by napcs** [comment]
@GreenPioneer Super swamped. Anyone willing to make a PR and test on Windows/OSX/Linux?

**Comment by dominicbarnes** [comment]
I would really like to get this moved forward, as I depend on this module for a project I'm working on.

I will see about getting the test suite run, I can check both OSX and Linux. I'm not really in the best position to try Windows though, can someone else help me with that?

**Comment by napcs** [comment]
@dominicbarnes I can test on Windows if you make the PR. I just don't want any surprises.

**Comment by napcs** [comment]
fixed by #76
