### ISSUE TITLE
I try to use HTTPS

### ISSUE THREAD

**Issue by crlshn** [napcs/node-livereload#71]
Hi I am trying to use the command line but serve https instead of the default http
where do I put the : 
```
const https = require('https');
const fs = require('fs');

const options = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

https.createServer(options, (req, res)
```

thanks in advance... If I can just edit some files to point to the keys.

**Comment by napcs** [comment]
No plans to support this with the command line version.
