### ISSUE TITLE
Support creating a server that does not automatically listen

### ISSUE THREAD

**Issue by dominicbarnes** [napcs/node-livereload#74]
The only public API (ie: `livereload.createServer()`) creates the server then immediately calls `server.listen()`. It would be great if I could bypass this behavior and call that myself.

**Comment by napcs** [comment]
@dominicbarnes What's the use case for this? I'm inclined to close this because this is really supposed to be a dirt simple implementation that just works. But I'm open to understanding use cases.

**Comment by dominicbarnes** [comment]
For example, a connect server (such as in your examples) doesn't automatically start, you need to call `server.listen()` first. I have a similar server wrapper that I'm making, and in `new Server()`, I'd like to initialize both the web server and the ws server, but would prefer to allow the caller to start it whenever it is ready.

**Comment by dominicbarnes** [comment]
Nice! Thanks :)
