### ISSUE TITLE
Allow for passing a callback to the server (for when it comes up)

### ISSUE THREAD

**Issue by dominicbarnes** [napcs/node-livereload#75]
It turns out that `ws.Server()` accepts a `callback` as the 2nd argument (after `options`) which is called after the server is up and ready to accept connections. It would be great to hook into this behavior via `livereload.createServer()`. (or, if #74 is accepted, then `server.listen()` should accept a `callback` parameter)

**Comment by napcs** [comment]
@dominicbarnes What's the use case? Why would we need this?

**Comment by dominicbarnes** [comment]
Currently, there's no way for me to know precisely when that server is up and accepting connections. You could probably argue that it's such a short time that it doesn't matter, but I prefer to `console.log('server is listening')` when the server truly is ready.

There should be no breaking API change required, would just like something like this to work:

```js
let server = livereload.createServer(function () {
  console.log('livereload server listening')
})
```

If you pass no callback, nothing changes. I would also just be ok with building on #74 by doing:

```js
let server = livereload.createServer({ autoStart: false })

server.listen(function () {
  console.log('livereload server listening')
})
```
