### ISSUE TITLE
exclusions ignored, CPU Usage constantly 100%

### ISSUE THREAD

**Issue by coolaj86** [napcs/node-livereload#80]
On OS X with node 4.x, 6.x, and the livereload 0.4.0 and 0.5.0

I was serving directly from a folder with a large `node_modules` inside and the CPU spiked to 100% and would take full seconds to respond to requests.

I tried adding `{ exclusions: [ 'node_modules', '.git' ] }` and it still went up to 100%.

I try a different folder with only a few files and it's not a problem.

**Comment by napcs** [comment]
Please answer the following:

1. What is the specific code you are using to watch files?
2. Are these files on your local hard drive or on a network share?

**Comment by coolaj86** [comment]
Here's the snippet from my code:

```js
      if (opts.livereload) {
        opts.lrPort = opts.lrPort || lrPort;
        var livereload = require('livereload');
        var server2 = livereload.createServer({
          https: opts.httpsOptions
        , port: opts.lrPort
        , exclusions: [ '.hg', '.git', '.svn', 'node_modules' ]
        });

        console.info("[livereload] watching " + pubdir);
        console.warn("WARNING: If CPU usage spikes to 100% it's because too many files are being watched");
        server2.watch(pubdir);
      }
```

And the files are on a local hard drive.

**Comment by napcs** [comment]
Please change your exclusions to only include your node_modules folder. We're already excluding git, svn, etc.

https://github.com/napcs/node-livereload/blob/master/lib/livereload.coffee#L30

Let me know if that makes any difference.

**Comment by napcs** [comment]
@coolaj86 any luck?

**Comment by coolaj86** [comment]
No luck.

**Comment by napcs** [comment]
I've released a new version (0.6.0). It uses a newer version of the file watcher. Can you let me know if it helps?

**Comment by coolaj86** [comment]
What's that sound? Can you hear it?

That's the sound of my CPU fan NOT RUNNING at 100%.

WIN!

**Comment by napcs** [comment]
Wonderful! Thanks for following up.
