### ISSUE TITLE
Does not work in command line when options are specified before path

### ISSUE THREAD

**Issue by Jokero** [napcs/node-livereload#84]
## What version are you using?
0.6.0

I run `livereload` in command line:
```sh
livereload --port 4444 public/
```
And include script to page:
```
<script src="//localhost:4444/livereload.js?snipver=1"></script>
```

## Expected result
Should apply changes (reload page)

## Actual result
WS connection is established (I see three messages), but server does not notify client about changes.

When I change arguments order (put path first)
```sh
livereload public/ --port 4444
```
livereload starts to work as expected:
```json
{"command":"reload","path":"/home/dmitry/dev/public/styles/styles.css","liveCSS":true,"originalPath":"","overrideURL":""}
```

**Comment by napcs** [comment]
This is expected behavior as shown in the documentation. Path first, followed by options,

**Comment by Jokero** [comment]
For me this is really unexpected behaviour, because I can do the following:
```sh
npm i -g express
npm i express -g

cp -r testdir/* testdir2
cp testdir/* testdir2 -r
```

And result is always the same

**Comment by Jokero** [comment]
About documentation: it just says that we have to use path if we specify options. Nothing about it must be first

**Comment by napcs** [comment]
I understand. But this is expected behavior until someone takes the time to rewrite the option parser. Feel free to take a crack at it.
