### ISSUE TITLE
Add 'alert' command support

### ISSUE THREAD

**Issue by veproza** [napcs/node-livereload#85]
For use as part of a build process, when the build script is watching files and running in background in some console, it would be useful to be able to send an **alert** message if something goes wrong in the build.

With the build console in the background (personally I have an editor on my first monitor and browser on the other, with no place left for console) the user has no way of knowing the build is failing and therefore why the reload is not happening. An alert fixes that with a very visible notification whenever I make a build-failing error.

I tried to get that into a pull request here: #86 . I'm not very proficient in OSS and Github though, so feel free to correct me in any way.

**Comment by napcs** [comment]
@veproza hey, thanks for this. I think you did a pretty great job with this commit. Your refactoring didn't break the tests and this is one part of the protocol I've been meaning to implement anyway. I'll see if the test suite for this needs some updating and then I'll merge this in.

**Comment by napcs** [comment]
Fixed by #86
