### ISSUE TITLE
Regexes in defaultexclusions are incorrect

### ISSUE THREAD

**Issue by dubeg** [napcs/node-livereload#92]
## What version are you using?
livereload 0.6.0

## Expected result
The default ignored directories (including `.git`) should be ignored by livereload.

## Actual result
They are not ignored.

## Note
I have a question about this particular [commit](https://github.com/napcs/node-livereload/commit/26b5d45f441141040df3cf3742bf239096ca1efd), which I thnk is the root of this issue. What did the author try to do with it? Did he want to ignore a directory named `git/` instead of `.git/`?

**Comment by napcs** [comment]
This particular commit happened before we swapped out the monitoring library. I haven't seen this behavior reflected when I run this, but I'm inclined to change the regex anyway since it just looks incorrect now. Thanks for reporting, and look for a fix soon.

**Comment by dubeg** [comment]
Alright, good to hear. 

I kept having livereload crash when git did something with `.git/index.lock`.
`Error: EPERM: operation not permitted, stat 'C:\Users\...\Projects\poorvs\.git\index.lock'`

**Comment by napcs** [comment]
Oh that's interesting..... also you're on Windows. Y'all seem to have all sorts of crazy things going on with the exclusions, historically. I'll see what I can do.

**Comment by dubeg** [comment]
Hehe. Well in this case it's pretty simple. The commit I mentioned above changed the regexes to match something like `\git/`, `\agit/`, `\.git/`, `\bgit/`, etc. It's just wrong. He probably had a good intention but I don't know what it was.

**Comment by napcs** [comment]
Closed by  1e82c8a
