### ISSUE TITLE
Is there a way to catch errors?

### ISSUE THREAD

**Issue by nfriend** [napcs/node-livereload#93]
If I start a second instance of a `node-livereload` server, I get the follow message and a stack trace, which is to be expected:

```bash
Error: listen EADDRINUSE :::35729
    ... stacktrace here ...
```

However, I can't figure out a way to catch and prevent this message from being printed in the console.  I've tried `try/catch`, but the error happens asynchronously (and probably in another process?).  

My use-case for this: I'd like to be able to catch the error and print a friendlier error message, like "Unable to start the LiveReload server!  This is most likely because you have another instance of the LiveReload server running on this port."

**Comment by napcs** [comment]
@nfriend How are you invoking the server? Through the CLI or are you using the API directly?

**Comment by nfriend** [comment]
I'm using the API directly:

```JavaScript
const livereload = require('livereload');

const server = livereload.createServer();
server.watch('path/to/watch');
```

**Comment by napcs** [comment]
@nfriend 0.7.0 is released. It now supports an error event you can watch. The examples/ folder has an example of this.
