### ISSUE TITLE
CLI does not work when installing with Yarn

### ISSUE THREAD

**Issue by arxpoetica** [napcs/node-livereload#97]
v0.6.2

## Expected result

Run from the command line:

`yarn global add livereload`

...which gives me the following install output:

```
yarn global v0.23.2
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "livereload@0.6.2" with binaries:
      - livereload
warning No license field
✨  Done in 2.88s.
```
(everything looks like it SHOULD be good, but...)

## Actual result

The binary does not appear to be registered to the command line. I keep getting the following:

```
livereload .
zsh: command not found: livereload
```

## Why is this important?

I would like to use Yarn, not npm, though I'm defaulting to npm for now. It took me quite some time to realize that this was a problem related to your installer not having love for Yarn.

**Comment by napcs** [comment]
Hi. Thanks for the detailed error report.

`yarn` is supposed to maintain compatibility with `npm`.  There's no installer for livereload other than the standard `package.json` file definition and structure.

I'm inclined to think this is a path issue on your setup. The `yarn` docs suggest you can specify a prefix:

```
 yarn global add livereload --prefix /usr/local
```

https://github.com/yarnpkg/yarn/issues/630 seems to spend a lot of time talking about issues like this. So does https://github.com/yarnpkg/yarn/issues/648

Best of luck.
