### ISSUE TITLE
Use EventSource instead of Web Sockets?

### ISSUE THREAD

**Issue by mroderick** [napcs/node-livereload#98]
I think this is a great project, thank you for all your efforts with this!

AFAICT from experimentation and research online, Safari on iOS doesn't use self-signed certificates for secure web socket connections. For scenarios where testing in iOS Safari over HTTPS is important, that makes using this module either impossible or quite expensive/cumbersome (using verified CA signed certificates for all developer machines).

However, an alternative mechanism exists: [EventSource](https://html.spec.whatwg.org/multipage/comms.html#the-eventsource-interface)

Here are some resources:

* Spec: https://html.spec.whatwg.org/multipage/comms.html#the-eventsource-interface
* https://developer.mozilla.org/en-US/docs/Web/API/EventSource
* http://caniuse.com/#search=eventsource
* https://github.com/Yaffle/EventSource

Would you consider a pull request to replace the transport mechanism to use EventSource instead of Web Sockets?

Some users would have to add a polyfill for testing in non-supporting browsers like IE/Edge/Opera Mini

**Comment by napcs** [comment]
Sounds like a great idea, but we can't do that. I don't control the LiveReload protocol, which uses Web sockets. This library has to remain compatible with that protocol, including the browser extensions. 

Sorry. :(

**Comment by mroderick** [comment]
Cheers!
