### ISSUE TITLE
high memory

### ISSUE THREAD

**Issue by wupengFEX** [napcs/node-livereload#99]
## What version are you using? (Don't say latest. Be specific.)
0.6.2
## Expected result
Stable memory
## Actual result
High memory
## Steps to reproduce issue
1. start watch;
```
server.watch([...])
```
2. refresh web page, the memory will rise some after every time you refresh;

![JS Stacj](https://cloud.githubusercontent.com/assets/8186657/25852452/f726af78-34fb-11e7-89d1-cbda7babdb64.jpg)

![memory](https://cloud.githubusercontent.com/assets/8186657/25852542/4919f18c-34fc-11e7-9149-43526fcd9bb5.jpg)

@napcs

**Comment by napcs** [comment]
Can't reproduce with a basic setup. You indicate you are starting it with

```
server.watch([...])
```

But I don't have a way to see what else is going on in the Node process.


Can you provide the following?

1. NodeJS version
2. OS version
3. A link to a demo app that reproduces this issue?

**Comment by wupengFEX** [comment]
- The code is as follows
```
let watches = [
    config.baseDir + '/**/*.html',
    config.baseDir + '/**/*.htm',
    config.baseDir + '/**/*.js',
    config.baseDir + '/**/*.less'
];
lrServer.watch(watches);
```
- Reappearance scene
There has more files,The more files are monitored, the more obvious the effect.

- Others
    - nodejs version: 6.7.0
    - os version: macos sierra 10.12

**Comment by napcs** [comment]
Thanks. I'll see what I can do about this. This wasn't designed to be watching multiple path globs like you're doing, so this will take some investigation.

You note that you manually refresh the page. Does the memory usage go up if you just change some JS or CSS files? I want to narrow down whether it's the watcher or the sockets.

**Comment by wupengFEX** [comment]
No matter what file I change there is a memory rise, but the rate of increase is different, the more files are getting bigger.

**Comment by wupengFEX** [comment]
@napcs Is there any conclusion?

**Comment by napcs** [comment]
@wupengFEX I can't seem to reproduce this. Does the memory ever go back down for you or hit a point where it stops growing? With a large number of files, it's definitely going to grow to a certain point. Can you give me an idea of how many files you have it watching?

**Comment by wupengFEX** [comment]
@napcs A few days ago I gave you an example on Facebook, It can reproduce the problem,You can check it, we can communicate in time if there has some problems!

**Comment by napcs** [comment]
@wupengFEX The example you provided me used another program that uses LiveReload. Please provide me a test case that recreates this issue using **only** LiveReload. I still cannot reproduce the issue on my machines.
